name: x509
description: Dart library for parsing and working with X.509 certificates.
version: 0.2.4+2
homepage: https://github.com/appsup-dart/x509
funding:
  - https://github.com/sponsors/rbellens

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  asn1lib:
    path: asn1lib
  quiver: ^3.0.0
  crypto_keys: ^0.3.0+1

dev_dependencies:
  test: ^1.0.0
  lints: ^5.0.0

false_secrets:
  - test/files/*
